Homework 2
================
Sarahy Martinez
09-29-2024

Libraries Used for this HW

``` r
library(tidyverse)
library(tidyr)
library(readxl)
```

## Problem 1

``` r
 NYC_transit =
  read_csv("./data/NYC_Transit_Subway_Entrance_AND_EXIT_DATA.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  relocate(line:entry, ada,vending) %>% 
  select(-division:-entrance_location, station_location) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE)) %>% 
  mutate(vending = ifelse(vending == "YES", TRUE, FALSE)) %>% 
  mutate(across(starts_with("route"), as.character)) %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name",
  ) %>% 
  relocate(station_name,station_location,route_number, route_name,line,entrance_type, entry, ada,vending)
```

This dataset contains the variables station name, station location,
train route number, routes,line, entrance type, entry, exit only,
vending, ada, station lat, and station long. I cleaned my data by using
clean names to fix the variable names, relocated the order of my
variables for legibility, selected my columns/ data of interest, mutated
the character variables from entry to logical, mutates the names of the
routes as characters because it wasn’t allowing me to run the pivot
function , then used the pivot_longer to tidy the data and combine route
numbers to one column and assign the routes their own column with the
station, and relocated again for legibility. Data is now tidy.

``` r
count(distinct(NYC_transit, station_name,line))
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1   465

``` r
transit_entry = 
  NYC_transit %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct()

transit_entry = NYC_transit %>% 
  filter( vending == "FALSE") %>% 
  pull(entry) %>% 
  mean()

A_train =
  NYC_transit %>% 
  filter(route_name == "A") %>% 
  distinct(station_name, line) 
nrow(A_train)
```

    ## [1] 60

``` r
A_train_ada =
  NYC_transit %>% 
  filter(route_name == "A", ada== TRUE) %>% 
  distinct(station_name, line) 
nrow(A_train_ada)
```

    ## [1] 17

- There are 465 distinct stations.
- There are 84 stations that are ADA compliant.
- There proportion of entrances/ exits without vending that allow
  entrance, is 0.377.
- There are 60 stations that serve the A train, and 17 are ADA
  compliant.

## Probem 2

Importing and reading the dataset

``` r
mister_trash_data = read_excel("./data/202409 Trash Wheel Collection Data New.xlsx", 
                               sheet=1,
                               skip = 1,
                               range= "A2:N653",
                               na = c("NA", ".", "")) %>% 
                            janitor::clean_names() %>% 
                            mutate(sports_balls = as.integer(round(sports_balls))) %>% 
                            mutate(year = as.numeric(year)) %>% 
                            mutate(trash = "mister_trash") 
```

``` r
professor_trash = read_excel("./data/202409 Trash Wheel Collection Data New.xlsx", 
                               sheet=2,
                               skip = 1,
                               range= "A2:M121",
                               na = c("NA", ".", "")) %>% 
                            janitor::clean_names() %>% 
                            mutate(year = as.numeric(year)) %>% 
                            mutate(trash = "professor_trash") 
```

``` r
gwynnda_trash = read_excel("./data/202409 Trash Wheel Collection Data New.xlsx", 
                               sheet=4,
                               skip = 1,
                               range= "A2:L265",
                               na = c("NA", ".", "")) %>% 
                            janitor::clean_names() %>% 
                            mutate(year = as.numeric(year)) %>% 
                            mutate(trash = "gwynnda_trash") 
```

``` r
trash_wheel_tidy = 
  bind_rows(professor_trash, gwynnda_trash, mister_trash_data) %>% 
  janitor::clean_names() %>% 
  select(trash, everything())

nrow(trash_wheel_tidy)
```

    ## [1] 1033

``` r
ncol(trash_wheel_tidy)
```

    ## [1] 15

``` r
summary(trash_wheel_tidy)
```

    ##     trash              dumpster        month                year     
    ##  Length:1033        Min.   :  1.0   Length:1033        Min.   :2014  
    ##  Class :character   1st Qu.: 86.0   Class :character   1st Qu.:2018  
    ##  Mode  :character   Median :199.0   Mode  :character   Median :2020  
    ##                     Mean   :245.7                      Mean   :2020  
    ##                     3rd Qu.:393.0                      3rd Qu.:2022  
    ##                     Max.   :651.0                      Max.   :2024  
    ##                                                        NA's   :1     
    ##       date                        weight_tons    volume_cubic_yards
    ##  Min.   :2014-05-16 00:00:00.0   Min.   :0.610   Min.   : 5.00     
    ##  1st Qu.:2018-04-16 00:00:00.0   1st Qu.:2.540   1st Qu.:15.00     
    ##  Median :2020-12-26 00:00:00.0   Median :3.080   Median :15.00     
    ##  Mean   :2020-05-11 15:06:58.5   Mean   :3.038   Mean   :15.08     
    ##  3rd Qu.:2022-11-04 18:00:00.0   3rd Qu.:3.553   3rd Qu.:15.00     
    ##  Max.   :2024-06-11 00:00:00.0   Max.   :5.620   Max.   :20.00     
    ##  NA's   :1                       NA's   :1       NA's   :1         
    ##  plastic_bottles  polystyrene    cigarette_butts  glass_bottles   
    ##  Min.   :   0    Min.   :    0   Min.   :     0   Min.   :  0.00  
    ##  1st Qu.: 980    1st Qu.:  230   1st Qu.:  2800   1st Qu.: 10.00  
    ##  Median :1900    Median :  640   Median :  4800   Median : 18.00  
    ##  Mean   :2201    Mean   : 1383   Mean   : 13296   Mean   : 20.92  
    ##  3rd Qu.:2900    3rd Qu.: 2045   3rd Qu.: 12000   3rd Qu.: 28.00  
    ##  Max.   :9830    Max.   :11528   Max.   :310000   Max.   :110.00  
    ##  NA's   :2       NA's   :2       NA's   :2        NA's   :265     
    ##   plastic_bags      wrappers     homes_powered    sports_balls  
    ##  Min.   :    0   Min.   :    0   Min.   : 0.00   Min.   : 0.00  
    ##  1st Qu.:  220   1st Qu.:  900   1st Qu.:39.00   1st Qu.: 6.00  
    ##  Median :  470   Median : 1440   Median :49.83   Median :12.00  
    ##  Mean   :  927   Mean   : 2246   Mean   :46.54   Mean   :13.98  
    ##  3rd Qu.: 1115   3rd Qu.: 2580   3rd Qu.:58.08   3rd Qu.:20.00  
    ##  Max.   :13450   Max.   :20100   Max.   :93.67   Max.   :56.00  
    ##  NA's   :2       NA's   :119     NA's   :70      NA's   :382

``` r
rowSums(is.na(trash_wheel_tidy))
```

    ##    [1]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
    ##   [25]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
    ##   [49]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
    ##   [73]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
    ##   [97]  1  1  1  1  1  1  7  1  1  1  1  1  1  1  1  1  1  1  2  2  2  2 13  3
    ##  [121]  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
    ##  [145]  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
    ##  [169]  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
    ##  [193]  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
    ##  [217]  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  2  2  2  2
    ##  [241]  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
    ##  [265]  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
    ##  [289]  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
    ##  [313]  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
    ##  [337]  2  2  2  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
    ##  [361]  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  0  0
    ##  [385]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [409]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [433]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [457]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [481]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [505]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [529]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [553]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [577]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [601]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [625]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [649]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [673]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [697]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [721]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [745]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [769]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [793]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [817]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [841]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [865]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [889]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [913]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [937]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [961]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ##  [985]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    ## [1009]  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
    ## [1033]  1

In this dataset we have 15 variables which include dumpster, month,
year, date, weight_tons, volume_cubic_yards, plastic_bottles,
polystyrene, cigarette_butts, glass_bottles, plastic_bags, wrappers,
homes_powered,sports_balls, and trash (to specify from which dataset).
There are a total of 1,033 observations (rows) and 15 columns. The
datasheets were individually imported, in mister trash I mutated the
year and same for the rest due to years being considered as a character
in one dataset and the others as numeric so I converted them all to
numeric and get the mean years, committed data is 2022. I also cleaned
the names for reasonable variable names and mutated again to create a
variable name to identify which dataset the trash is from.

``` r
total_weight_prof =  trash_wheel_tidy %>% 
                     filter(trash == "professor_trash") %>% 
                     summarise(total_weight = sum(weight_tons, na.rm = TRUE))

print(total_weight_prof)
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         247.

``` r
total_cigs_gwn =  trash_wheel_tidy %>% 
                     filter(trash == "gwynnda_trash", year == "2022", month == "June") %>% 
                     summarise(cigarette_butts = sum(cigarette_butts, na.rm = TRUE))
print(total_cigs_gwn)
```

    ## # A tibble: 1 × 1
    ##   cigarette_butts
    ##             <dbl>
    ## 1           18120

- The total weight of trash collected by Professor trash wheel was
  246.76 tons.
- In the month of June 2022 Gwynnda collected 18,120 cigarette butts.

## Problem 3

``` r
bakers_df = 
  read_csv("./data/bakers.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  separate(baker_name, into = c("first_name", "last_name"), sep = " ") %>% 
  select(- last_name) %>% 
  rename(bakers = first_name) %>% 
  drop_na()
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
bakes_df = 
  read_csv("./data/bakes.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  rename(bakers = baker) %>% 
  drop_na()
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
results_df = 
  read_csv("./data/results.csv", skip = 3, col_names = FALSE,na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  rename(series = x1,episode = x2, baker = x3, technical = x4, result = x5, ) %>% 
  rename( bakers = baker) %>% 
  drop_na()
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): X3, X5
    ## dbl (3): X1, X2, X4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
GBB_merged_ = 
  full_join(results_df, bakes_df, by = c("bakers", "series", "episode")) %>% 
  full_join(x= ., bakers_df, by =c("series","bakers"))
```

## problem 3, part 2

``` r
views = 
  read_csv("./data/viewers.csv",na = c("NA", ".", ""))  %>% 
  janitor::clean_names() %>% 
  rename( season_1 = series_1, season_2 = series_2, season_3 = series_3, season_4 = series_4, season_5 = series_5, season_6 = series_6, season_7 = series_7, season_8 = series_8, season_9 = series_9, season_10 = series_10) %>% 
  head(10)
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mean(pull(views, season_1), na.rm = TRUE)
```

    ## [1] 2.77

``` r
mean(pull(views, season_5), na.rm = TRUE)
```

    ## [1] 10.0393

- The average viewership in season 1 was 2.77
- The average viewership in season 5 was 10.0393
